### ISSUE TITLE
22.07.07 이후 읽을 책 선정하기

### ISSUE THREAD

**Issue by youngreal** [Stacked-Book/select#1]
전에 말씀드렸던이유로 오브젝트를 다음스터디로 진행하려고하는데 
혹시나 선호하지않은 분이 많을수도 있겠다는생각에 남겨봅니다

현재 본인이 읽고싶은 책을 2개 선정해서 
책이름과 그 책을 선정한이유와 적어주세요 (오브젝트 진행하는것을 찬성하시다면 포함하셔도 됩니다)

그리고 오브젝트로 진행하는것에 찬/반 의견도 주시면 좋을것같아요

**Comment by lee-ji-hoon** [comment]
다들 자바를 사용하신다면 
- 모던 자바 인 액션

자바를 제외한다면
- 운영체제(공룡책) / 클린코드 이 두 가지 입니다!

`오브젝트`로 진행하는 것에 대한 찬/반은 **찬성**입니다. `객체지향의 진실과 오해`도 좋지만 `오브젝트` 책과는 다르게 간단한 예시로 설명을 하다보니 네트워크와 비슷하게 될 것 같아 객체지향책을 한다고하면 `오브젝트` 책으로 하는게 좋아 보입니다.

**Comment by youngreal** [comment]
@lee-ji-hoon 모던 자바 인액션 좋네요. 저도 오브젝트를 하게된다면 향후 모던자바인액션,클린코드를 읽어보고 싶긴합니다 
운영체제는 전에한번 단톡에서 OS관련책으로 스터디진행 안내 드렸었는데  현재 건창님과 재은님과 진행하고 있긴합니다. 
책의 이름은 리눅스와 OS구조이지만 리눅스에 대한 설명보다는 리눅스를 기반으로 OS내용을 다루게되는 책입니다
그러다보니 책에있는것 뿐만아니라 운영체제의 중요한 개념들을 질답하는시간을 가지고 토의하는 시간을 가지고있습니다. 
저도 이과정에서 공룡책을 참고하고있고 지금은 5장쯤 보고있네요  

운영체제와 관련된 스터디를 현재 3명이 진행하고있다보니 아마 공룡책을가지고 스터디를 열게되면 니즈가 조금 떨어질 가능성이 있을것같네요

**Comment by lee-ji-hoon** [comment]
@youngreal 
### 운영체제와 관련된 스터디를 현재 3명이 진행하고있다보니 아마 공룡책을가지고 스터디를 열게되면 니즈가 조금 떨어질 가능성이 있을것같네요
네 아무래도 이미 OS를 하고 계셔서 별로인 것 같긴 합니다.   
저번에 레포지토리 봤을 때 이슈에 다양한 내용들이 많았어서 저도 그 내용 따로 보면서 공부하겠습니다!

---
### 추가로 책 적으실때 적으신이유에 대해서도 간단하게 말씀해주시면 좋을것 같습니다.
- `모던 자바 인액션` 은 평소 자바 코드를 짤 때 stream이나 Lambda 부터 시작해서 java 8 9 10의 내용들을 제대로 다뤄 본 적이 없어서 해당 내용을 다른 사람들과 이야기 해보면서 서로의 코드를 보면 좋을 것 같다고 생각해서 추천을 했습니다.
- `공룡책` 은 아무래도 이미 OS를 하고 있으시니 패스해도 괜찮을 것 같습니다. 저도 단순히 면접 정도에서 나오는 질문을 커버하기 위해서였는데 처음에 책 이름만 보고 리눅스이길래 패스했었는데 아쉽네요!..
- `클린코드` 말 그대로 좋은 코드가 무엇일까? 라는 생각을 하면서 코드를 짜고 있음에도 혼자 하다보니 확실하지가 않았고 그래서 선정하게 됐습니다. 아무래도 이런책은 혼자 읽는 것보다 다양한 사람들과 스터디를 진행해서 하는게 좀 더 효율적이라고 생각해서 선정했습니다!

**Comment by youngreal** [comment]
> 
관심있으시다면 지금 열려있는 이슈내용이라도 답글 달아보시고 참여고려해보세요ㅎㅎ 
스터디를 딱히 준비해야할것도 없기때문에 부담도 많지는않은 스터디입니다 네트워크책 끝나는 시간에 간단하게 모임가지고 이슈에대해서 이야기합니다

**Comment by this-is-spear** [comment]
저는 자바 웹 프로그래밍 Next Step/ 오브젝트가 좋습니다.

- `자바 웹 프로그래밍 Next Step`을 선택한 이유는 스프링의 동작 구조를 이해하기 좋은 책이라 선정했습니다.
- `오브젝트`는 객체 지향 관점으로 프로젝트를 설계하는데 도움이 될 것 같아 선정했습니다.

그 외에도 모던 자바 인 액션과 클린코드도 개인적으로 좋습니다. 👍

**Comment by youngreal** [comment]
@this-is-spear 
저도 자바웹프로그래밍 next step책은 목말라있습니다 ㅎㅎ..  안그래도 건창님이 사신것 보고 같이 해보자고 말씀드려볼까했었는데 차마 스터디에서 다른분들 설득할 자신이 없었습니다
nextstep의 [만들면서 배우는Spring](https://edu.nextstep.camp/c/4YUvqn9V/) 과정이 이책을 바탕으로 진행하는것 같더라구요 

요거는 스터디 책으로 선정안되더라도 다른 비는시간이 있으시다면 언제든 저도 껴주시길 부탁드립니다

**Comment by lee-ji-hoon** [comment]
@youngreal 
> > 
> 
> 관심있으시다면 이슈내용이라도 답글 달아보시고 참여고려해보세요ㅎㅎ 참여하신다면 속도를 조금조절하겠습니다 스터디를 딱히 준비해야할것도 없기때문에 부담도 많지는않은 스터디입니다 네트워크책 끝나는 시간에 간단하게 모임가지고 이슈에대해서 이야기합니다

네 그러면 이번주 네트워크 끝나고서 초반 이슈부터 천천히 답글달아 보겠습니다!

**Comment by Jaeeun1083** [comment]
- **오브젝트** : 객체지향 프로그래밍에 대해 잘 설명되어 있는 책인 것 같습니다.
- **클린코드** : 좋은 책이고 개발자라면 읽어야할 책이라고 알고있지만 쉽게 시작하지 못하는 이유는 책의 두께와 난이도인 것 같습니다. 스터디할 때 읽기 좋은책이라는 생각이 듭니다.
- **데이터 중심 애플리케이션 설계** : 노마드코더 유튜버에서 추천한 책인데 읽으려다 너무 어려워 포기했습니다. 읽어야겠다 생각만하고 있던 책이라 리스트에 올려봅니다..


지훈님이 올려주신 **모던 자바 인 액션**이나 백기선님 유튜브 강의 중에 "**스터디할래**"라는 자바 관련 스터디를 진행하시는게 있는데 공부하기 좋은 영상인 것 같습니다
